theme: minima
title: Wayne's Page
author: Wayne
email: 1194884805@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Gain growth step by step. Go forward together!

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  WayneWWWWW # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
